name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: The resize handle doesn't work when...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install @jeremy-boschen/react-adjustable-panels
        2. Create a PanelGroup with...
        3. Try to drag the handle...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The panel should resize smoothly
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: The panel jumps around and doesn't resize
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of @jeremy-boschen/react-adjustable-panels are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: react-version
    attributes:
      label: React Version
      description: Which version of React are you using?
      placeholder: "19.0.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) does this occur in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code example that reproduces the issue
      placeholder: |
        ```tsx
        import { Panel, PanelGroup } from '@jeremy-boschen/react-adjustable-panels';

        function App() {
          return (
            <PanelGroup direction="horizontal">
              <Panel defaultSize="50%">Left</Panel>
              <Panel defaultSize="50%">Right</Panel>
            </PanelGroup>
          );
        }
        ```
      render: tsx

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem
